/*
 * MMA1211.h
 *
 *  Created on: Mar 20, 2021
 *      Author: Jeff
 */

#ifndef HARDWARE_INTERFACES_HARDWARE_INTERFACES_SRC_MMA1211_H_
#define HARDWARE_INTERFACES_HARDWARE_INTERFACES_SRC_MMA1211_H_



#endif /* HARDWARE_INTERFACES_HARDWARE_INTERFACES_SRC_MMA1211_H_ */
